# Generated by Django 4.2.7 on 2025-09-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('is_capital', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoadConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('road_type', models.CharField(choices=[('highway', 'Highway'), ('expressway', 'Expressway'), ('federal', 'Federal Road'), ('state', 'State Road'), ('local', 'Local Road')], default='federal', max_length=50)),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_roads', to='cities.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_roads', to='cities.city')),
            ],
            options={
                'ordering': ['from_city__name', 'to_city__name'],
                'unique_together': {('from_city', 'to_city')},
            },
        ),
    ]
